 Waiting for host: postgres 5432
 Astro Runtime Version: 11.3.0
 OSError while attempting to symlink the latest log directory
 [[34m2024-11-27T17:28:00.225+0000[0m] {[34mconfiguration.py:[0m1050} WARNING[0m - section/key [openlineage/namespace] not found in config[0m
 [[34m2024-11-27T17:28:24.017+0000[0m] {[34mplugin.py:[0m88} INFO[0m - Creating DB tables for astronomer.airflow.version_check.plugin[0m
 [[34m2024-11-27T17:28:24.053+0000[0m] {[34mplugin.py:[0m99} ERROR[0m - Error creating tables[0m
 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
     self.dialect.do_execute(
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
     cursor.execute(statement, parameters)
 psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
 DETAIL:  Key (typname, typnamespace)=(astro_version_check, 2200) already exists.
 
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/astronomer/airflow/version_check/plugin.py", line 90, in create_db_tables
     metadata.create_all(
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
     bind._run_ddl_visitor(
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 348, in _run_ddl_visitor
     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
     return meth(obj, **kw)
            ^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 855, in visit_metadata
     self.traverse_single(
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
     return meth(obj, **kw)
            ^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 899, in visit_table
     self.connection.execute(
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 286, in execute
     return self._execute_20(
            ^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
     return meth(self, args_10style, kwargs_10style, execution_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
     return connection._execute_ddl(
            ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
     ret = self._execute_context(
           ^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
     self._handle_dbapi_exception(
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
     util.raise_(
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
     raise exception
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
     self.dialect.do_execute(
   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
     cursor.execute(statement, parameters)
 sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
 DETAIL:  Key (typname, typnamespace)=(astro_version_check, 2200) already exists.
 
 [SQL: 
 CREATE TABLE astro_version_check (
 	singleton BOOLEAN NOT NULL, 
 	last_checked TIMESTAMP WITH TIME ZONE, 
 	last_checked_by TEXT, 
 	CONSTRAINT astro_version_check_pkey PRIMARY KEY (singleton)
 )
 
 ]
 (Background on this error at: https://sqlalche.me/e/14/gkpj)
 [[34m2024-11-27T17:28:30.005+0000[0m] {[34mconfiguration.py:[0m1050} WARNING[0m - section/key [openlineage/namespace] not found in config[0m
 [[34m2024-11-27T17:28:33.506+0000[0m] {[34mplugin.py:[0m32} WARNING[0m - Astro managed secrets backend is disabled[0m
 
 airflow command error: argument GROUP_OR_COMMAND: `airflow upgradedb` command, has been removed, please use `airflow db upgrade`, see help above.
 Usage: airflow [-h] GROUP_OR_COMMAND ...
 
 Positional Arguments:
   GROUP_OR_COMMAND
 
     Groups
       config         View configuration
       connections    Manage connections
       dags           Manage DAGs
       db             Database operations
       jobs           Manage jobs
       pools          Manage pools
       providers      Display providers
       roles          Manage roles
       tasks          Manage tasks
       users          Manage users
       variables      Manage variables
 
     Commands:
       cheat-sheet    Display cheat sheet
       dag-processor  Start a standalone Dag Processor instance
       info           Show information about current Airflow and environment
       kerberos       Start a kerberos ticket renewer
       plugins        Dump information about loaded plugins
       rotate-fernet-key
                      Rotate encrypted connection credentials and variables
       scheduler      Start a scheduler instance
       standalone     Run an all-in-one copy of Airflow
       sync-perm      Update permissions for existing roles and optionally DAGs
       triggerer      Start a triggerer instance
       version        Show the version
       webserver      Start a Airflow webserver instance
 
 Options:
   -h, --help         show this help message and exit
 Waiting for host: postgres 5432
 Astro Runtime Version: 11.3.0
 [[34m2024-11-27T17:28:41.708+0000[0m] {[34mconfiguration.py:[0m1050} WARNING[0m - section/key [openlineage/namespace] not found in config[0m
 [[34m2024-11-27T17:28:51.191+0000[0m] {[34mplugin.py:[0m32} WARNING[0m - Astro managed secrets backend is disabled[0m
 /usr/local/lib/python3.11/site-packages/airflow/cli/commands/db_command.py:69 DeprecationWarning: `db upgrade` is deprecated. Use `db migrate` instead.
 DB: postgresql://postgres:***@postgres:5432
 Performing upgrade to the metadata database postgresql://postgres:***@postgres:5432
 [[34m2024-11-27T17:28:52.000+0000[0m] {[34mmigration.py:[0m216} INFO[0m - Context impl PostgresqlImpl.[0m
 [[34m2024-11-27T17:28:52.000+0000[0m] {[34mmigration.py:[0m219} INFO[0m - Will assume transactional DDL.[0m
 [[34m2024-11-27T17:28:52.003+0000[0m] {[34mdb.py:[0m1623} INFO[0m - Creating tables[0m
 INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
 INFO  [alembic.runtime.migration] Will assume transactional DDL.
 WARNI [cosmos.airflow.graph] Unavailable conversion function for <DbtResourceType.UNIT_TEST> (node <unit_test.jaffle_shop.agg_orders.test_amount_sum>). Define a converter function using render_config.node_converters.
 /usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py:351 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
 /usr/local/lib/python3.11/site-packages/snowflake/snowpark/session.py:2712 UserWarning: Pandas Dataframe has non-standard index of type <class 'pandas.core.indexes.base.Index'> which will not be written. Consider changing the index to pd.RangeIndex(start=0,...,step=1) or call reset_index() to keep index as column(s)
 the url is: https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/2023-01-09?adjusted=true&apiKey=Em7xrXc5QX01uQqD29xxTrVZXfrrjC6Q
 the results dict is:
 type is:  <class 'list'>
 [{'T': 'TTMI', 'v': 394280, 'vw': 16.1078, 'o': 15.96, 'c': 16.08, 'h': 16.335, 'l': 15.96, 't': 1673298000000, 'n': 5416}, {'T': 'OEC', 'v': 485157, 'vw': 19.0627, 'o': 18.67, 'c': 18.98, 'h': 19.43, 'l': 18.45, 't': 1673298000000, 'n': 8130}, {'T': 'USDU', 'v': 642813, 'vw': 25.8745, 'o': 25.92, 'c': 25.88, 'h': 25.95, 'l': 25.8204, 't': 1673298000000, 'n': 2417}, {'T': 'BWXT', 'v': 389669, 'vw': 57.4657, 'o': 58.15, 'c': 57.28, 'h': 58.18, 'l': 57.025, 't': 1673298000000, 'n': 7325}, {'T': 'WRB', 'v': 1947042.0, 'vw': 48.8506, 'o': 49.5267, 'c': 48.6533, 'h': 49.5867, 'l': 48.3933, 't': 1673298000000, 'n': 15947}]
 the col TTMI is: <class 'str'>
 the col 394280 is: <class 'int'>
 the col 16.1078 is: <class 'float'>
 the col 15.96 is: <class 'float'>
 the col 16.08 is: <class 'float'>
 the col 16.335 is: <class 'float'>
 the col 15.96 is: <class 'float'>
 the col 1673298000000 is: <class 'int'>
 the col 5416 is: <class 'int'>
 Data loaded successfully
 Database migrating done!
 [[34m2024-11-27T17:31:38.729+0000[0m] {[34mconfiguration.py:[0m1050} WARNING[0m - section/key [openlineage/namespace] not found in config[0m
 [[34m2024-11-27T17:31:42.522+0000[0m] {[34mplugin.py:[0m32} WARNING[0m - Astro managed secrets backend is disabled[0m
   ____________       _____________
  ____    |__( )_________  __/__  /________      __
 ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
 ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
 [[34m2024-11-27T17:31:43.378+0000[0m] {[34mtask_context_logger.py:[0m63} INFO[0m - Task context logging is enabled[0m
 [[34m2024-11-27T17:31:43.378+0000[0m] {[34mexecutor_loader.py:[0m235} INFO[0m - Loaded executor: LocalExecutor[0m
 [2024-11-27 17:31:43 +0000] [220] [INFO] Starting gunicorn 22.0.0
 [2024-11-27 17:31:43 +0000] [220] [INFO] Listening at: http://[::]:8793 (220)
 [2024-11-27 17:31:43 +0000] [220] [INFO] Using worker: sync
 [[34m2024-11-27T17:31:43.591+0000[0m] {[34mscheduler_job_runner.py:[0m796} INFO[0m - Starting the scheduler[0m
 [[34m2024-11-27T17:31:43.592+0000[0m] {[34mscheduler_job_runner.py:[0m803} INFO[0m - Processing each file at most -1 times[0m
 [2024-11-27 17:31:43 +0000] [223] [INFO] Booting worker with pid: 223
 [2024-11-27 17:31:43 +0000] [235] [INFO] Booting worker with pid: 235
 [[34m2024-11-27T17:31:45.203+0000[0m] {[34mmanager.py:[0m170} INFO[0m - Launched DagFileProcessorManager with pid: 360[0m
 [[34m2024-11-27T17:31:45.205+0000[0m] {[34mscheduler_job_runner.py:[0m1595} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
 [[34m2024-11-27T17:31:45.218+0000[0m] {[34msettings.py:[0m60} INFO[0m - Configured default timezone UTC[0m
 [[34m2024-11-27T17:31:59.613+0000[0m] {[34mupdate_checks.py:[0m186} INFO[0m - Checking for new version of Astronomer Runtime, previous check was performed at None[0m
 [[34m2024-11-27T17:32:01.546+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 12.4.0 in update document[0m
 [[34m2024-11-27T17:32:01.550+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 12.3.0 in update document[0m
 [[34m2024-11-27T17:32:01.554+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 12.2.0 in update document[0m
 [[34m2024-11-27T17:32:01.560+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 12.1.1 in update document[0m
 [[34m2024-11-27T17:32:01.565+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 12.1.0 in update document[0m
 [[34m2024-11-27T17:32:01.567+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 12.0.0 in update document[0m
 [[34m2024-11-27T17:32:01.570+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.14.0 in update document[0m
 [[34m2024-11-27T17:32:01.573+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.13.0 in update document[0m
 [[34m2024-11-27T17:32:01.574+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.12.0 in update document[0m
 [[34m2024-11-27T17:32:01.576+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.11.0 in update document[0m
 [[34m2024-11-27T17:32:01.580+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.10.1 in update document[0m
 [[34m2024-11-27T17:32:01.586+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.10.0 in update document[0m
 [[34m2024-11-27T17:32:01.589+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.9.0 in update document[0m
 [[34m2024-11-27T17:32:01.593+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.8.0 in update document[0m
 [[34m2024-11-27T17:32:01.595+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.7.0 in update document[0m
 [[34m2024-11-27T17:32:01.605+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.6.0 in update document[0m
 [[34m2024-11-27T17:32:01.609+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.5.0 in update document[0m
 [[34m2024-11-27T17:32:01.615+0000[0m] {[34mupdate_checks.py:[0m201} INFO[0m - Found 11.4.0 in update document[0m
 [[34m2024-11-27T17:32:01.631+0000[0m] {[34mupdate_checks.py:[0m141} INFO[0m - A new version of Astronomer Runtime is available[0m
 [[34m2024-11-27T17:32:01.632+0000[0m] {[34mupdate_checks.py:[0m142} INFO[0m - Check finished, next check in 86400.0 seconds[0m
 [[34m2024-11-27T17:36:45.330+0000[0m] {[34mscheduler_job_runner.py:[0m1595} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
